import type { Metadata } from "next";
import {Inter,Roboto} from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Providers from "@/redux/Providers";
import { ThemeProvider } from "@/components/Application/Admin/ThemeProvider";
import { Bounce} from 'react-toastify';
const roboto=Roboto({
  subsets:["latin"],
  variable:"--font-roboto",
  weight:["100","200","300","400","500","600","700","800","900"]
})

const inter=Inter({
  subsets:["latin"],
  variable:"--font-inter",
  weight:["100","200","300","400","500","600","700","800","900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
     
      <body
        className={`${roboto.variable} `}
      >
        
         <ThemeProvider
    attribute="class"
    defaultTheme="system"
    enableSystem
    disableTransitionOnChange

    >
        
        <Providers>
       <ToastContainer
position="top-center"
autoClose={2000}
hideProgressBar
newestOnTop={false}
closeOnClick
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="colored"
transition={Bounce}
/>
        
        
        {children}
        </Providers>


        </ThemeProvider>

      </body>
      
    </html>
  );
}
